### ISSUE TITLE
DB and Result classes are tied to a single implementation when using DBAL

### ISSUE THREAD

**Issue by iamthefox** [voku/simple-mysqli#45]
#### What is this feature about (expected vs actual behaviour)?

DB class is tied to a specific `\Doctrine\DBAL\Statement` implementation when using DBAL as a parent connection. 

This makes it impossible to use with libraries like https://github.com/facile-it/doctrine-mysql-come-back impossible to use since they are wrapping DBAL connection, statement and some other classes with it's own implementation. 

For example if you look at `src/voku/db/DB.php:L1891` you will see that it's checking if result is an instance of `\Doctrine\DBAL\Statement`. When using library above you get different implementation of `Doctrine\DBAL\Driver\Statement` interface.   

#### Does it take minutes, hours or days to fix?

Not sure how big is the scope of this change would be but I am interested in writing up a PR for this if you are open to this change.

**Comment by voku** [comment]
Hi, I like to use interfaces instead of classes to check against, but mostly the classes has more implemented methods than the interface and for i.e. ```getWrappedStatement()``` I didn't find something in the interface at all. :-/ So I ignored the error from phpstan. What do you think of this: https://github.com/voku/simple-mysqli/commit/46623e254980447f9a51c12a5a5b00751a38ff7e
