### ISSUE TITLE
avoid @ operator

### ISSUE THREAD

**Issue by JBlond** [voku/simple-mysqli#8]
It would be nicer to use a try catch arround mysqli_connect instead of @mysqli_connect

**Comment by voku** [comment]
"PHP does not report mysqli or PDO errors by default because that information is highly sensitive, displaying it to a user is a great way to learn how to inject malicious data.

MYSQLI_REPORT_ERROR tells it to turn on the errors and MYSQLI_REPORT_STRICT tells it to convert those errors into Exceptions. This will give you a full report of the error message, so never do this in production environments."

-> and I don't want to see something like this: "mysql_connect() [function.mysql-connect]: Access denied for user 'secure_user'@'localhost' (using password: YES)" :/

PS: maybe we can activate this only for developer or only for local-developer ??

**Comment by JBlond** [comment]
Would be using only MYSQLI_REPORT_STRICT a solution so the try catch would work without the @ ?

**Comment by voku** [comment]
https://github.com/voku/simple-mysqli/commit/13c79800c18f80b440c44ea8034a08fa89b3153c

-> but I read the documentation that php will also throw an exception, so I still use the "@" for the connect-function ...

**Comment by JBlond** [comment]
Yes exception! But the exception surpresses the warning and the try catch catches the exception. So unless you print the stuff from the exception the user will see the message you have in $this->_displayError

Try it with this small script

```
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

try{
      mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
      $this->link = mysqli_connect(
        'localhost',
        'root',
        'wrong',
        'mysql',
        3306
      );
    } catch(Exception $exception){
      echo 'WHOOPS';
    }
```

**Comment by voku** [comment]
oki... :) then it's working as expected, because we will check if the current user will see the error-message via "checkForDev()" in the "_displayError()"-method

```
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

try {
  mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
  $this->link = @mysqli_connect(
    'localhost',
    'root',
    'wrong',
    'mysql',
    3306
  );
} catch(Exception $exception){
  if (DB::checkForDev() === true) {
    echo 'WHOOPS';
  }
}
```

**Comment by voku** [comment]
@JBlond thx for the feedback ... for now I will close this issue, also if we could use more "Exceptions" for other methods :|

**Comment by JBlond** [comment]
Sure close it, but why don't you remove the @ sign?
